From:lipinskiboris/de-nf
Bootstrap:docker

%labels
    MAINTAINER **Lipinski-B** <**boris.lipinski@etu.univ-lyon1.fr**>
    DESCRIPTION Image Singularity contenant tout les softwares nécessaires pour l'execution du pipeline DE-nf
    VERSION latest
